#pragma once

#include <juce_audio_processors/juce_audio_processors.h>
#include "pogged_dsp.h"

// Thin JUCE wrapper around the host-agnostic DSP core (src/pogged_dsp.{h,cpp}),
// the same core compiled into the LV2 plugin. Parameters use APVTS with IDs
// identical to the LV2 .ttl symbols, so state stays consistent across formats.
class PoggedAudioProcessor : public juce::AudioProcessor
{
public:
    PoggedAudioProcessor();
    ~PoggedAudioProcessor() override;

    void prepareToPlay(double sampleRate, int samplesPerBlock) override;
    void releaseResources() override {}
    bool isBusesLayoutSupported(const BusesLayout&) const override;
    void processBlock(juce::AudioBuffer<float>&, juce::MidiBuffer&) override;

    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override { return true; }

    const juce::String getName() const override { return "Pogged"; }
    bool acceptsMidi() const override  { return false; }
    bool producesMidi() const override { return false; }
    bool isMidiEffect() const override { return false; }
    double getTailLengthSeconds() const override { return 0.1; }

    // Factory presets — the same set as the LV2 .ttl presets
    // (see juce/pogged_presets.h, generated by tools/gen_presets.py).
    int getNumPrograms() override;
    int getCurrentProgram() override { return currentProgram; }
    void setCurrentProgram(int) override;
    const juce::String getProgramName(int) override;
    void changeProgramName(int, const juce::String&) override {}

    void getStateInformation(juce::MemoryBlock&) override;
    void setStateInformation(const void*, int) override;

    juce::AudioProcessorValueTreeState apvts;

private:
    static juce::AudioProcessorValueTreeState::ParameterLayout createLayout();

    PoggedDsp* dsp = nullptr;
    double currentSampleRate = 0.0;
    // 3 channels: 0 = mono in, 1 = out L, 2 = out R.
    juce::AudioBuffer<float> scratch;
    int currentProgram = 0;

    // Cached raw-parameter atomics (denormalised values, ready for PoggedParams).
    std::atomic<float>* pDry    = nullptr;
    std::atomic<float>* pSub1   = nullptr;
    std::atomic<float>* pSub2   = nullptr;
    std::atomic<float>* pUp1    = nullptr;
    std::atomic<float>* pUp2    = nullptr;
    std::atomic<float>* pDetune = nullptr;
    std::atomic<float>* pAttack = nullptr;
    std::atomic<float>* pSens   = nullptr;
    std::atomic<float>* pCutoff = nullptr;
    std::atomic<float>* pQ      = nullptr;
    std::atomic<float>* pOut    = nullptr;
    std::atomic<float>* pUp5    = nullptr;
    std::atomic<float>* pPanDry  = nullptr;
    std::atomic<float>* pPanSub1 = nullptr;
    std::atomic<float>* pPanSub2 = nullptr;
    std::atomic<float>* pPanUp5  = nullptr;
    std::atomic<float>* pPanUp1  = nullptr;
    std::atomic<float>* pPanUp2  = nullptr;
    std::atomic<float>* pSpread  = nullptr;
    std::atomic<float>* pFiltMode = nullptr;
    std::atomic<float>* pFiltEnv  = nullptr;
    std::atomic<float>* pFiltEnvA = nullptr;
    std::atomic<float>* pFiltEnvD = nullptr;
    std::atomic<float>* pFiltSens = nullptr;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(PoggedAudioProcessor)
};
